### ISSUE TITLE
AttributeError: 'NoneType'

### ISSUE THREAD

**Issue by UnSpotibleShadow** [DAzVise/modmail-plugins#1122]
The plugin started acting up since right now and my discord went ham because people couldn't get their roles in.

Here is the log after reboot, after trying to assign and remove a role through the menu, If you have any questions, you could reply to my DM on Discord ;)

> 2020-10-30T15:34:25.917535+00:00 app[worker.1]:     await member.remove_roles(role)
2020-10-30T15:34:25.917535+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'remove_roles'
2020-10-30T15:34:26.368785+00:00 app[worker.1]: 10/30/20 15:34:26 __main__[1142] - ERROR: Ignoring exception in on_raw_reaction_add.
2020-10-30T15:34:26.369520+00:00 app[worker.1]: 10/30/20 15:34:26 __main__[1143] - ERROR: Unexpected exception:
2020-10-30T15:34:26.369521+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-30T15:34:26.369524+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
2020-10-30T15:34:26.369525+00:00 app[worker.1]:     await coro(*args, **kwargs)
2020-10-30T15:34:26.369526+00:00 app[worker.1]:   File "/app/plugins/DAzVise/modmail-plugins/reaction-role-master/reaction-role.py", line 285, in on_raw_reaction_add
2020-10-30T15:34:26.369526+00:00 app[worker.1]:     if member.bot:
2020-10-30T15:34:26.369527+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'bot'
2020-10-30T15:35:35.463872+00:00 app[worker.1]: 10/30/20 15:35:35 __main__[1142] - ERROR: Ignoring exception in on_raw_reaction_add.
2020-10-30T15:35:35.464320+00:00 app[worker.1]: 10/30/20 15:35:35 __main__[1143] - ERROR: Unexpected exception:
2020-10-30T15:35:35.464321+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-30T15:35:35.464322+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
2020-10-30T15:35:35.464322+00:00 app[worker.1]:     await coro(*args, **kwargs)
2020-10-30T15:35:35.464323+00:00 app[worker.1]:   File "/app/plugins/DAzVise/modmail-plugins/reaction-role-master/reaction-role.py", line 285, in on_raw_reaction_add
2020-10-30T15:35:35.464324+00:00 app[worker.1]:     if member.bot:
2020-10-30T15:35:35.464324+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'bot'
2020-10-30T15:35:41.445558+00:00 app[worker.1]: 10/30/20 15:35:41 __main__[1142] - ERROR: Ignoring exception in on_raw_reaction_remove.
2020-10-30T15:35:41.445987+00:00 app[worker.1]: 10/30/20 15:35:41 __main__[1143] - ERROR: Unexpected exception:
2020-10-30T15:35:41.445988+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-30T15:35:41.445989+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
2020-10-30T15:35:41.445990+00:00 app[worker.1]:     await coro(*args, **kwargs)
2020-10-30T15:35:41.445990+00:00 app[worker.1]:   File "/app/plugins/DAzVise/modmail-plugins/reaction-role-master/reaction-role.py", line 335, in on_raw_reaction_remove
2020-10-30T15:35:41.445991+00:00 app[worker.1]:     await member.remove_roles(role)
2020-10-30T15:35:41.445991+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'remove_roles'

**Comment by UnSpotibleShadow** [comment]
For future reference, if anyone else ever has this issue. DAZ pointed me towards the server intents.

> Enable all privelleged intents in developer portal > Open app  > Bot and restart your bot.
